"""
scraper.py
----------
URL scraper for MOSAIC. Uses Playwright (headless Chromium) to load pages
like a real browser, which gets around sites that block direct image downloads.
Falls back to newspaper3k if Playwright fails.

Supports:
  - News articles (Playwright + newspaper3k fallback)
  - Reddit posts (no API key needed — uses Reddit's public .json endpoint)
  - Twitter/X posts (via Nitter — open source Twitter frontend, no API key needed)

Unsupported (API restrictions):
  - Instagram (Meta Graph API required)
  - Facebook (Meta Graph API required)
  - TikTok (no text scraping support)

get_scraped_data(url) is a pure standalone function with no Streamlit
dependencies — safe to call directly from Flask or any other backend.
"""

import re
import requests
from io import BytesIO
from urllib.parse import urlparse, unquote
from PIL import Image
from newspaper import Article


# ── Helpers ───────────────────────────────────────────────────────────────────

def _blank_image():
    """Returns a plain white 224x224 RGB image as a fallback when no image is found."""
    return Image.new('RGB', (224, 224), color=(255, 255, 255))


def _fetch_image(url):
    """
    Downloads an image from a URL and returns it as a PIL RGB image.
    Falls back to a blank image if the download fails or the URL is empty.
    """
    if not url:
        return _blank_image()
    try:
        resp = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        return Image.open(BytesIO(resp.content)).convert("RGB")
    except Exception:
        return _blank_image()


def _clean_text(text):
    """
    Cleans scraped text to remove noise that can confuse the ensemble.
    Removes timestamps, short fragments, navigation text, and site boilerplate.
    """
    timestamp_pattern = re.compile(
        r'^\s*(\d{1,2}:\d{2}(\s*[APap][Mm])?|Updated.*\d|\d+\s*(min|hour|hrs?|sec)s?\s*ago)\s*$',
        re.IGNORECASE
    )
    nav_keywords = [
        'click here', 'read more', 'subscribe', 'sign in', 'log in',
        'share this', 'follow us', 'advertisement', 'skip to', 'jump to',
        'load more', 'show more', 'see all', 'view all', 'back to top',
        'audio version of this article', 'mispronunciations can occur',
        'generated by ai-based technology', 'continually review and improve',
        'javascript must be enabled', 'please enable javascript',
        'cookies to improve your experience',
    ]

    lines = text.split('\n')
    cleaned = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if timestamp_pattern.match(stripped):
            continue
        if len(stripped) < 40:
            continue
        if any(kw in stripped.lower() for kw in nav_keywords):
            continue
        cleaned.append(stripped)

    return '\n\n'.join(cleaned).strip()


def _is_live_page(url):
    """Detects if a URL is likely a live update / live blog page."""
    live_patterns = [
        'live-update', 'live-blog', 'live-coverage', 'live-news',
        'breaking-news', 'real-time', '/live/', '-live-'
    ]
    return any(p in url.lower() for p in live_patterns)


def _playwright_browser(p):
    """Creates a Playwright browser with anti-detection settings."""
    browser = p.chromium.launch(
        headless=True,
        args=[
            '--disable-blink-features=AutomationControlled',
            '--no-sandbox',
            '--disable-http2',
        ]
    )
    context = browser.new_context(
        user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                   '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        extra_http_headers={'Accept-Language': 'en-US,en;q=0.9'}
    )
    return browser, context


# ── Platform detection ────────────────────────────────────────────────────────

def _detect_platform(url):
    """Returns a platform string based on the URL domain."""
    url_lower = url.lower()
    if "reddit.com" in url_lower or "redd.it" in url_lower:
        return "reddit"
    if "twitter.com" in url_lower or "x.com" in url_lower:
        return "twitter"
    if "instagram.com" in url_lower:
        return "instagram"
    if "facebook.com" in url_lower or "fb.com" in url_lower:
        return "facebook"
    if "tiktok.com" in url_lower:
        return "tiktok"
    return "article"


def _twitter_to_nitter(url):
    """
    Converts a Twitter/X URL to a Nitter URL.
    Also strips /photo/N suffixes since Nitter shows all photos on the main post page.
    e.g. https://x.com/user/status/123/photo/1 → https://nitter.poast.org/user/status/123
    """
    # Strip /photo/N or /video/N suffixes
    url = re.sub(r'/(photo|video)/\d+$', '', url.rstrip('/'))
    # Replace domain
    url = re.sub(r'https?://(www\.)?(twitter\.com|x\.com)', 'https://nitter.poast.org', url)
    return url


# ── Playwright scraper ────────────────────────────────────────────────────────

def _scrape_with_playwright(url):
    """
    Loads the page using headless Chromium via Playwright.
    Extracts article text via newspaper3k on the rendered HTML,
    and finds the lead image from og:image or the largest <img> tag.
    Returns (text, image_url) or raises on failure.
    """
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser, context = _playwright_browser(p)
        page = context.new_page()

        # Block unnecessary resources to speed up loading
        page.route("**/*.{woff,woff2,ttf,otf}", lambda route: route.abort())
        page.route("**/ads/**", lambda route: route.abort())

        page.goto(url, wait_until="domcontentloaded", timeout=20000)
        page.wait_for_timeout(2000)

        html = page.content()

        # Try og:image first (most reliable lead image)
        og_image = page.evaluate("""
            () => {
                const og = document.querySelector('meta[property="og:image"]');
                return og ? og.getAttribute('content') : null;
            }
        """)

        # Fallback: find largest img tag
        if not og_image:
            og_image = page.evaluate("""
                () => {
                    const imgs = Array.from(document.querySelectorAll('img'));
                    const scored = imgs
                        .filter(img => img.naturalWidth > 200 && img.naturalHeight > 200)
                        .sort((a, b) => (b.naturalWidth * b.naturalHeight) - (a.naturalWidth * a.naturalHeight));
                    return scored.length > 0 ? scored[0].src : null;
                }
            """)

        browser.close()

    # Parse text from rendered HTML using newspaper3k
    article = Article(url)
    article.set_html(html)
    article.parse()

    raw_text = f"{article.title}\n\n{article.text}".strip()
    return raw_text, og_image


# ── Article scraper ───────────────────────────────────────────────────────────

# Sites known to block Playwright — skip straight to newspaper3k
_PLAYWRIGHT_BLOCKLIST = [
    "cbc.ca",
]

def _scrape_article(url):
    """
    Scrapes a news article. Tries Playwright first for full browser rendering,
    falls back to newspaper3k if Playwright fails or is blocklisted.
    """
    image_url = None
    raw_text  = None

    skip_playwright = any(site in url.lower() for site in _PLAYWRIGHT_BLOCKLIST)

    if not skip_playwright:
        try:
            raw_text, image_url = _scrape_with_playwright(url)
        except Exception as e:
            print(f"[scraper] Playwright failed ({e}), falling back to newspaper3k")

    # Fall back to newspaper3k if Playwright failed or was skipped
    if not raw_text or len(raw_text.strip()) < 100:
        try:
            article = Article(url)
            article.download()
            article.parse()
            raw_text  = f"{article.title}\n\n{article.text}".strip()
            image_url = image_url or article.top_image
        except Exception as e:
            raise RuntimeError(f"Failed to scrape article: {e}")

    # Clean the text
    full_text = _clean_text(raw_text)
    if len(full_text) < 100:
        full_text = raw_text.split('\n')[0]

    # Download the image
    image   = _fetch_image(image_url)
    is_blank = image_url is None or (
        image.size == (224, 224) and image.getpixel((0, 0)) == (255, 255, 255)
    )

    warning = None
    if _is_live_page(url):
        warning = (
            "⚠ This appears to be a live update page. "
            "Results may be less reliable — consider pasting the article text manually."
        )
    elif is_blank:
        warning = (
            "⚠ No image could be extracted from this page. "
            "Results may be less reliable — consider uploading the article image manually."
        )

    return {"text": full_text, "image": image, "warning": warning}


# ── Twitter scraper ───────────────────────────────────────────────────────────

# Nitter instance to use — change this if the instance goes down
_NITTER_INSTANCE = "nitter.poast.org"

def _scrape_twitter(url):
    """
    Scrapes a Twitter/X post via Nitter (open source Twitter frontend).
    No API key required. Converts the Twitter URL to a Nitter URL and uses
    Playwright to get past Nitter's browser verification challenge.

    Extracts:
      - Tweet text
      - First attached media image (if any)

    Falls back to a warning if no image is found (text-only tweets).
    """
    from playwright.sync_api import sync_playwright

    nitter_url = _twitter_to_nitter(url)
    print(f"[scraper] Twitter → Nitter: {nitter_url}")

    with sync_playwright() as p:
        browser, context = _playwright_browser(p)
        page = context.new_page()

        page.goto(nitter_url, wait_until="networkidle", timeout=30000)
        page.wait_for_timeout(5000)  # wait for JS verification to complete

        # Extract tweet text from the main post container
        try:
            tweet_text = page.inner_text('.main-tweet .tweet-content')
        except Exception:
            # Fallback: grab all text and clean it
            tweet_text = page.inner_text('body')

        # Extract media images (actual tweet photos, not profile pics)
        media_images = page.eval_on_selector_all(
            'img',
            'imgs => imgs.map(i => i.src).filter(s => s.includes("media"))'
        )

        browser.close()

    # Clean the tweet text
    tweet_text = tweet_text.strip()
    if not tweet_text:
        raise RuntimeError("Could not extract text from this tweet.")

    # Get the first media image
    image_url = media_images[0] if media_images else None

    # Nitter proxies images through its own domain — convert to direct Twitter URL
    # e.g. https://nitter.poast.org/pic/media%2FHEv1mTsaUAAq-Fs.jpg
    # → https://pbs.twimg.com/media/HEv1mTsaUAAq-Fs.jpg
    if image_url and _NITTER_INSTANCE in image_url:
        try:
            # Extract the path after /pic/
            pic_path = image_url.split('/pic/')[1]
            # Decode URL encoding
            pic_path = unquote(pic_path)
            # Strip query params like ?name=small&format=webp
            pic_path = pic_path.split('?')[0]
            # Build direct Twitter image URL
            image_url = f"https://pbs.twimg.com/{pic_path}"
        except Exception:
            pass

    image    = _fetch_image(image_url)
    is_blank = image_url is None or (
        image.size == (224, 224) and image.getpixel((0, 0)) == (255, 255, 255)
    )
    warning = (
        "⚠ No image found in this tweet. "
        "Results may be less reliable — consider uploading an image manually."
    ) if is_blank else None

    return {"text": tweet_text, "image": image, "warning": warning}


# ── Reddit scraper ────────────────────────────────────────────────────────────

def _scrape_reddit(url):
    """
    Scrapes a Reddit post using Reddit's public .json endpoint.
    No API key required — Reddit exposes post data by appending .json to any post URL.
    """
    json_url = url.rstrip('/') + '.json'
    headers  = {"User-Agent": "MOSAIC/1.0"}

    try:
        resp = requests.get(json_url, headers=headers, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        post = data[0]['data']['children'][0]['data']
    except Exception as e:
        raise RuntimeError(f"Failed to fetch Reddit post: {e}")

    title    = post.get('title', '').strip()
    selftext = post.get('selftext', '').strip()
    full_text = f"{title}\n\n{selftext}".strip() if selftext else title

    if not full_text:
        raise RuntimeError("Reddit post has no text content.")

    image     = _blank_image()
    post_url  = post.get('url', '')
    image_url = None

    if post_url and any(post_url.lower().endswith(ext) for ext in ('.jpg', '.jpeg', '.png', '.webp', '.gif')):
        image_url = post_url
    elif post.get('preview'):
        try:
            image_url = post['preview']['images'][0]['source']['url'].replace('&amp;', '&')
        except (KeyError, IndexError):
            pass

    if not image_url and post_url and not any(post_url.lower().endswith(ext) for ext in ('.jpg', '.jpeg', '.png', '.webp', '.gif')):
        try:
            article = Article(post_url)
            article.download()
            article.parse()
            if article.top_image:
                image_url = article.top_image
        except Exception:
            pass

    if image_url:
        image = _fetch_image(image_url)

    is_blank = image_url is None or (
        image.size == (224, 224) and image.getpixel((0, 0)) == (255, 255, 255)
    )
    warning = (
        "⚠ No image found in this Reddit post. "
        "Results may be less reliable — consider uploading an image manually."
    ) if is_blank else None

    return {"text": full_text, "image": image, "warning": warning}

# ── Unsupported platforms ─────────────────────────────────────────────────────

def _unsupported_platform(platform):
    messages = {
        "instagram": "Instagram cannot be scraped. Please copy and paste the post text manually.",
        "tiktok":    "TikTok does not support text scraping. Please copy and paste any caption manually.",
        "facebook":  "Facebook requires a paid API. Please copy and paste the post text manually.",
    }
    raise RuntimeError(messages.get(platform, f"Unsupported platform: {platform}"))


# ── Main entry point ──────────────────────────────────────────────────────────

def get_scraped_data(url: str) -> dict:
    """
    Main scraper entry point. Detects the URL type and routes to the
    appropriate scraper. Pure standalone function — no Streamlit dependencies.

    Returns a dict with:
      - text    : cleaned article/post text (str)
      - image   : PIL RGB image (lead image or blank 224x224 fallback)
      - warning : optional user-facing warning string, or None

    Raises RuntimeError with a user-friendly message on failure.
    """
    platform = _detect_platform(url)

    if platform == "article":
        return _scrape_article(url)
    elif platform == "reddit":
        return _scrape_reddit(url)
    elif platform == "twitter":
        return _scrape_twitter(url)
    elif platform == "facebook":
        return _scrape_facebook(url)
    else:
        _unsupported_platform(platform)