"""
scraper.py
----------
URL scraper for MOSAIC. Uses Playwright (headless Chromium) to load pages
like a real browser, which gets around sites that block direct image downloads.
Falls back to newspaper3k if Playwright fails.

Supports:
  - News articles (Playwright + newspaper3k fallback)
  - Reddit posts (no API key needed — uses Reddit's public .json endpoint)
  - Facebook public posts (BeautifulSoup)

Unsupported (API restrictions):
  - Twitter/X (paid API only)
  - Instagram (Meta Graph API required)
  - TikTok (no text scraping support)

get_scraped_data(url) is a pure standalone function with no Streamlit
dependencies — safe to call directly from Flask or any other backend.
"""

import re
import requests
from io import BytesIO
from PIL import Image
from newspaper import Article


# ── Helpers ───────────────────────────────────────────────────────────────────

def _blank_image():
    """Returns a plain white 224x224 RGB image as a fallback when no image is found."""
    return Image.new('RGB', (224, 224), color=(255, 255, 255))


def _fetch_image(url):
    """
    Downloads an image from a URL and returns it as a PIL RGB image.
    Falls back to a blank image if the download fails or the URL is empty.
    """
    if not url:
        return _blank_image()
    try:
        resp = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        return Image.open(BytesIO(resp.content)).convert("RGB")
    except Exception:
        return _blank_image()


def _clean_text(text):
    """
    Cleans scraped text to remove noise that can confuse the ensemble.
    Removes timestamps, short fragments, navigation text, and site boilerplate.
    """
    timestamp_pattern = re.compile(
        r'^\s*(\d{1,2}:\d{2}(\s*[APap][Mm])?|Updated.*\d|\d+\s*(min|hour|hrs?|sec)s?\s*ago)\s*$',
        re.IGNORECASE
    )
    nav_keywords = [
        'click here', 'read more', 'subscribe', 'sign in', 'log in',
        'share this', 'follow us', 'advertisement', 'skip to', 'jump to',
        'load more', 'show more', 'see all', 'view all', 'back to top',
        'audio version of this article', 'mispronunciations can occur',
        'generated by ai-based technology', 'continually review and improve',
        'javascript must be enabled', 'please enable javascript',
        'cookies to improve your experience',
    ]

    lines = text.split('\n')
    cleaned = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if timestamp_pattern.match(stripped):
            continue
        if len(stripped) < 40:
            continue
        if any(kw in stripped.lower() for kw in nav_keywords):
            continue
        cleaned.append(stripped)

    return '\n\n'.join(cleaned).strip()


def _is_live_page(url):
    """Detects if a URL is likely a live update / live blog page."""
    live_patterns = [
        'live-update', 'live-blog', 'live-coverage', 'live-news',
        'breaking-news', 'real-time', '/live/', '-live-'
    ]
    return any(p in url.lower() for p in live_patterns)


# ── Platform detection ────────────────────────────────────────────────────────

def _detect_platform(url):
    """Returns a platform string based on the URL domain."""
    url_lower = url.lower()
    if "reddit.com" in url_lower or "redd.it" in url_lower:
        return "reddit"
    if "twitter.com" in url_lower or "x.com" in url_lower:
        return "twitter"
    if "instagram.com" in url_lower:
        return "instagram"
    if "facebook.com" in url_lower or "fb.com" in url_lower:
        return "facebook"
    if "tiktok.com" in url_lower:
        return "tiktok"
    return "article"


# ── Playwright scraper ────────────────────────────────────────────────────────

def _scrape_with_playwright(url):
    """
    Loads the page using headless Chromium via Playwright.
    Extracts article text via newspaper3k on the rendered HTML,
    and finds the lead image from og:image or the largest <img> tag.
    Returns (text, image_url) or raises on failure.
    """
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=[
                "--disable-http2",
                "--disable-blink-features=AutomationControlled",
                "--no-sandbox",
            ]
        )
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            extra_http_headers={"Accept-Language": "en-US,en;q=0.9"}
        )
        page = context.new_page()

        # Block unnecessary resources to speed up loading
        page.route("**/*.{woff,woff2,ttf,otf}", lambda route: route.abort())
        page.route("**/ads/**", lambda route: route.abort())

        page.goto(url, wait_until="domcontentloaded", timeout=20000)
        page.wait_for_timeout(2000)

        html = page.content()

        # Try og:image first (most reliable lead image)
        og_image = page.evaluate("""
            () => {
                const og = document.querySelector('meta[property="og:image"]');
                return og ? og.getAttribute('content') : null;
            }
        """)

        # Fallback: find largest img tag
        if not og_image:
            og_image = page.evaluate("""
                () => {
                    const imgs = Array.from(document.querySelectorAll('img'));
                    const scored = imgs
                        .filter(img => img.naturalWidth > 200 && img.naturalHeight > 200)
                        .sort((a, b) => (b.naturalWidth * b.naturalHeight) - (a.naturalWidth * a.naturalHeight));
                    return scored.length > 0 ? scored[0].src : null;
                }
            """)

        browser.close()

    # Parse text from rendered HTML using newspaper3k
    article = Article(url)
    article.set_html(html)
    article.parse()

    raw_text = f"{article.title}\n\n{article.text}".strip()
    return raw_text, og_image


# ── Article scraper ───────────────────────────────────────────────────────────

# Sites known to block Playwright — skip straight to newspaper3k
_PLAYWRIGHT_BLOCKLIST = [
    "cbc.ca",
]

def _scrape_article(url):
    """
    Scrapes a news article. Tries Playwright first for full browser rendering,
    falls back to newspaper3k if Playwright fails or is blocklisted.
    """
    image_url = None
    raw_text  = None

    skip_playwright = any(site in url.lower() for site in _PLAYWRIGHT_BLOCKLIST)

    if not skip_playwright:
        try:
            raw_text, image_url = _scrape_with_playwright(url)
        except Exception as e:
            print(f"[scraper] Playwright failed ({e}), falling back to newspaper3k")

    # Fall back to newspaper3k if Playwright failed or was skipped
    if not raw_text or len(raw_text.strip()) < 100:
        try:
            article = Article(url)
            article.download()
            article.parse()
            raw_text  = f"{article.title}\n\n{article.text}".strip()
            image_url = image_url or article.top_image
        except Exception as e:
            raise RuntimeError(f"Failed to scrape article: {e}")

    # Clean the text
    full_text = _clean_text(raw_text)
    if len(full_text) < 100:
        full_text = raw_text.split('\n')[0]

    # Download the image
    image   = _fetch_image(image_url)
    is_blank = image_url is None or (
        image.size == (224, 224) and image.getpixel((0, 0)) == (255, 255, 255)
    )

    warning = None
    if _is_live_page(url):
        warning = (
            "⚠ This appears to be a live update page. "
            "Results may be less reliable — consider pasting the article text manually."
        )
    elif is_blank:
        warning = (
            "⚠ No image could be extracted from this page. "
            "Results may be less reliable — consider uploading the article image manually."
        )

    return {"text": full_text, "image": image, "warning": warning}


# ── Reddit scraper ────────────────────────────────────────────────────────────

def _scrape_reddit(url):
    """
    Scrapes a Reddit post using Reddit's public .json endpoint.
    No API key required — Reddit exposes post data by appending .json to any post URL.

    Extracts:
      - title + selftext (body) for text posts
      - title + image URL for image/link posts
    """
    # Normalise URL: strip trailing slash then append .json
    json_url = url.rstrip('/') + '.json'
    headers  = {"User-Agent": "MOSAIC/1.0"}

    try:
        resp = requests.get(json_url, headers=headers, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        post = data[0]['data']['children'][0]['data']
    except Exception as e:
        raise RuntimeError(f"Failed to fetch Reddit post: {e}")

    # Build text from title + body
    title    = post.get('title', '').strip()
    selftext = post.get('selftext', '').strip()
    full_text = f"{title}\n\n{selftext}".strip() if selftext else title

    if not full_text:
        raise RuntimeError("Reddit post has no text content.")

    # Try to get image from post URL or preview
    image     = _blank_image()
    post_url  = post.get('url', '')
    image_url = None

    if post_url and any(post_url.lower().endswith(ext) for ext in ('.jpg', '.jpeg', '.png', '.webp', '.gif')):
        image_url = post_url
    elif post.get('preview'):
        try:
            # Reddit encodes & as &amp; in preview URLs
            image_url = post['preview']['images'][0]['source']['url'].replace('&amp;', '&')
        except (KeyError, IndexError):
            pass

    if image_url:
        image = _fetch_image(image_url)
    elif post_url and not any(post_url.lower().endswith(ext) for ext in ('.jpg', '.jpeg', '.png', '.webp', '.gif')):
        # Link post — try to grab the lead image from the linked article
        try:
            article = Article(post_url)
            article.download()
            article.parse()
            if article.top_image:
                image = _fetch_image(article.top_image)
                image_url = article.top_image
        except Exception:
            pass

    is_blank = image_url is None or (
        image.size == (224, 224) and image.getpixel((0, 0)) == (255, 255, 255)
    )
    warning = (
        "⚠ No image found in this Reddit post. "
        "Results may be less reliable — consider uploading an image manually."
    ) if is_blank else None

    return {"text": full_text, "image": image, "warning": warning}


# ── Facebook scraper (Does not work since it needs credentials) ──────────────────────────────────────────────────────────

def _scrape_facebook(url):
    """
    Scrapes a public Facebook post using BeautifulSoup.
    Only works for public posts — private posts and login-gated content
    will fail gracefully with an error message.

    Extracts post text from Open Graph meta tags and the lead image.
    """
    try:
        from bs4 import BeautifulSoup
    except ImportError:
        raise RuntimeError("beautifulsoup4 is not installed. Run: pip install beautifulsoup4")

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    try:
        resp = requests.get(url, headers=headers, timeout=10)
        resp.raise_for_status()
    except Exception as e:
        raise RuntimeError(
            f"Could not load Facebook page: {e}. "
            "This may be a private post — please paste the text manually."
        )

    soup = BeautifulSoup(resp.text, 'html.parser')

    # Try og:description for post text (most reliable for public posts)
    text = None
    og_desc = soup.find('meta', property='og:description')
    if og_desc and og_desc.get('content'):
        text = og_desc['content'].strip()

    # Fallback: og:title
    if not text:
        og_title = soup.find('meta', property='og:title')
        if og_title and og_title.get('content'):
            text = og_title['content'].strip()

    if not text:
        raise RuntimeError(
            "Could not extract text from this Facebook post. "
            "It may be private or login-gated — please paste the text manually."
        )

    # Get lead image from og:image
    image_url = None
    og_image  = soup.find('meta', property='og:image')
    if og_image and og_image.get('content'):
        image_url = og_image['content']

    image    = _fetch_image(image_url)
    is_blank = image_url is None or (
        image.size == (224, 224) and image.getpixel((0, 0)) == (255, 255, 255)
    )
    warning = (
        "⚠ No image found in this Facebook post. "
        "Results may be less reliable — consider uploading an image manually."
    ) if is_blank else None

    return {"text": text, "image": image, "warning": warning}


# ── Unsupported platforms ─────────────────────────────────────────────────────

def _unsupported_platform(platform):
    messages = {
        "twitter":   "Twitter/X requires a paid API. Please copy and paste the tweet text manually.",
        "instagram": "Instagram cannot be scraped. Please copy and paste the post text manually.",
        "tiktok":    "TikTok does not support text scraping. Please copy and paste any caption manually.",
    }
    raise RuntimeError(messages.get(platform, f"Unsupported platform: {platform}"))


# ── Main entry point ──────────────────────────────────────────────────────────

def get_scraped_data(url: str) -> dict:
    """
    Main scraper entry point. Detects the URL type and routes to the
    appropriate scraper. Pure standalone function — no Streamlit dependencies.

    Returns a dict with:
      - text    : cleaned article/post text (str)
      - image   : PIL RGB image (lead image or blank 224x224 fallback)
      - warning : optional user-facing warning string, or None

    Raises RuntimeError with a user-friendly message on failure.
    """
    platform = _detect_platform(url)

    if platform == "article":
        return _scrape_article(url)
    elif platform == "reddit":
        return _scrape_reddit(url)
    elif platform == "facebook":
        return _scrape_facebook(url)
    else:
        _unsupported_platform(platform)