"""
scraper.py
----------
URL scraper for MOSAIC. Uses Playwright (headless Chromium) to load pages
like a real browser, which gets around sites that block direct image downloads
(e.g. CBC, Globe and Mail). Falls back to newspaper3k if Playwright fails.

Supports standard news articles only for now. Twitter/Instagram/Facebook/Reddit
are not currently supported — the user is prompted to paste text manually.

Includes text cleaning to remove timestamp fragments, short lines, and other
noise from live update pages that can confuse the ensemble.
"""

import re
import requests
from io import BytesIO
from PIL import Image
from newspaper import Article


# ── Helpers ───────────────────────────────────────────────────────────────────

def _blank_image():
    """Returns a plain white 224x224 RGB image as a fallback when no image is found."""
    return Image.new('RGB', (224, 224), color=(255, 255, 255))


def _fetch_image(url):
    """
    Downloads an image from a URL and returns it as a PIL RGB image.
    Falls back to a blank image if the download fails or the URL is empty.
    """
    if not url:
        return _blank_image()
    try:
        resp = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        return Image.open(BytesIO(resp.content)).convert("RGB")
    except Exception:
        return _blank_image()


def _clean_text(text):
    """
    Cleans scraped article text to remove noise that can confuse the ensemble.
    Removes timestamps, short fragments, navigation text, and common site
    boilerplate (e.g. CBC audio disclaimers).
    """
    timestamp_pattern = re.compile(
        r'^\s*(\d{1,2}:\d{2}(\s*[APap][Mm])?|Updated.*\d|\d+\s*(min|hour|hrs?|sec)s?\s*ago)\s*$',
        re.IGNORECASE
    )
    nav_keywords = [
        'click here', 'read more', 'subscribe', 'sign in', 'log in',
        'share this', 'follow us', 'advertisement', 'skip to', 'jump to',
        'load more', 'show more', 'see all', 'view all', 'back to top',
        'audio version of this article', 'mispronunciations can occur',
        'generated by ai-based technology', 'continually review and improve',
        'javascript must be enabled', 'please enable javascript',
        'cookies to improve your experience',
    ]

    lines = text.split('\n')
    cleaned = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if timestamp_pattern.match(stripped):
            continue
        if len(stripped) < 40:
            continue
        if any(kw in stripped.lower() for kw in nav_keywords):
            continue
        cleaned.append(stripped)

    result = '\n\n'.join(cleaned)
    return result.strip()


def _is_live_page(url):
    """
    Detects if a URL is likely a live update / live blog page.
    These pages produce fragmented text that can mislead the ensemble.
    """
    live_patterns = [
        'live-update', 'live-blog', 'live-coverage', 'live-news',
        'breaking-news', 'real-time', '/live/', '-live-'
    ]
    return any(p in url.lower() for p in live_patterns)


# ── Platform detection ────────────────────────────────────────────────────────

def _detect_platform(url):
    url_lower = url.lower()
    if "reddit.com" in url_lower or "redd.it" in url_lower:
        return "reddit"
    if "twitter.com" in url_lower or "x.com" in url_lower:
        return "twitter"
    if "instagram.com" in url_lower:
        return "instagram"
    if "facebook.com" in url_lower or "fb.com" in url_lower:
        return "facebook"
    if "tiktok.com" in url_lower:
        return "tiktok"
    return "article"


# ── Playwright scraper ────────────────────────────────────────────────────────

def _scrape_with_playwright(url):
    """
    Loads the page using headless Chromium via Playwright.
    Extracts the article text using newspaper3k on the rendered HTML,
    and finds the lead image from og:image or the largest <img> tag.
    Returns (text, image_url) or raises on failure.
    """
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        )
        page = context.new_page()

        # Block unnecessary resources to speed up loading
        page.route("**/*.{woff,woff2,ttf,otf}", lambda route: route.abort())
        page.route("**/ads/**", lambda route: route.abort())

        page.goto(url, wait_until="domcontentloaded", timeout=20000)

        # Wait a moment for lazy-loaded content
        page.wait_for_timeout(2000)

        html = page.content()

        # Try to get og:image first (most reliable lead image)
        og_image = page.evaluate("""
            () => {
                const og = document.querySelector('meta[property="og:image"]');
                return og ? og.getAttribute('content') : null;
            }
        """)

        # Fallback: find largest img tag
        if not og_image:
            og_image = page.evaluate("""
                () => {
                    const imgs = Array.from(document.querySelectorAll('img'));
                    const scored = imgs
                        .filter(img => img.naturalWidth > 200 && img.naturalHeight > 200)
                        .sort((a, b) => (b.naturalWidth * b.naturalHeight) - (a.naturalWidth * a.naturalHeight));
                    return scored.length > 0 ? scored[0].src : null;
                }
            """)

        browser.close()

    # Parse text from rendered HTML using newspaper3k
    article = Article(url)
    article.set_html(html)
    article.parse()

    raw_text = f"{article.title}\n\n{article.text}".strip()
    return raw_text, og_image


# ── Main article scraper ──────────────────────────────────────────────────────

def _scrape_article(url):
    """
    Scrapes a news article. Tries Playwright first for full browser rendering,
    falls back to newspaper3k direct download if Playwright fails.
    Cleans text and detects live update pages.
    """
    image_url = None
    raw_text  = None
    used_playwright = False

    # Try Playwright first
    try:
        raw_text, image_url = _scrape_with_playwright(url)
        used_playwright = True
    except Exception as e:
        print(f"[scraper] Playwright failed ({e}), falling back to newspaper3k")

    # Fall back to newspaper3k if Playwright failed or got no text
    if not raw_text or len(raw_text.strip()) < 100:
        try:
            article = Article(url)
            article.download()
            article.parse()
            raw_text  = f"{article.title}\n\n{article.text}".strip()
            image_url = image_url or article.top_image
        except Exception as e:
            raise RuntimeError(f"Failed to scrape article: {e}")

    # Clean the text
    full_text = _clean_text(raw_text)
    if len(full_text) < 100:
        # If cleaning removed too much, use raw title only
        full_text = raw_text.split('\n')[0]

    # Download the image
    image = _fetch_image(image_url)
    is_blank = (image_url is None or image.size == (224, 224) and
                image.getpixel((0, 0)) == (255, 255, 255))

    # Build warning
    warning = None
    if _is_live_page(url):
        warning = (
            "⚠ This appears to be a live update page. "
            "Results may be less reliable — consider pasting the article text manually."
        )
    elif is_blank:
        warning = (
            "⚠ No image could be extracted from this page. "
            "Results may be less reliable — consider uploading the article image manually."
        )

    return {"text": full_text, "image": image, "warning": warning}


def _unsupported_platform(platform):
    messages = {
        "reddit":    "Reddit scraping is coming soon. Please copy and paste the post text manually for now.",
        "twitter":   "Twitter/X requires a paid API. Please copy and paste the tweet text manually.",
        "instagram": "Instagram cannot be scraped. Please copy and paste the post text manually.",
        "facebook":  "Facebook cannot be scraped. Please copy and paste the post text manually.",
        "tiktok":    "TikTok does not support text scraping. Please copy and paste any caption manually.",
    }
    raise RuntimeError(messages.get(platform, f"Unsupported platform: {platform}"))


# ── Main entry point ──────────────────────────────────────────────────────────

def get_scraped_data(url):
    """
    Main scraper entry point. Returns a dict with 'text', 'image', and 'warning' keys.

    - text    : cleaned article text
    - image   : PIL RGB image (lead image or blank fallback)
    - warning : optional string shown in the UI (live pages, missing images)
    """
    platform = _detect_platform(url)

    if platform == "article":
        return _scrape_article(url)
    else:
        _unsupported_platform(platform)